# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-25 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_project', to='scheduling.Project', verbose_name='\u043f\u0440\u043e\u0435\u043a\u0442'),
            preserve_default=False,
        ),
    ]
