# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-27 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_auto_20170325_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predecessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u043f\u0440\u0435\u0434\u0448\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u0438\u043a',
                'verbose_name_plural': '\u043f\u0440\u0435\u0434\u0448\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u0438\u043a\u0438',
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='predecessors',
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.FloatField(help_text='\u0432 \u0447\u0430\u0441\u0430\u0445', verbose_name='\u0434\u043b\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='predecessor',
            name='predecessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_task', to='scheduling.Task', verbose_name='\u043f\u0440\u0435\u0434\u0448\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u0438\u043a'),
        ),
        migrations.AddField(
            model_name='predecessor',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Task', verbose_name='\u043e\u0441\u043d\u043e\u0432\u043d\u043e\u0439 \u0442\u0430\u0441\u043a'),
        ),
    ]
