# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-28 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_auto_20170327_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predecessor',
            options={'verbose_name': '\u041f\u0440\u0435\u0434\u0448\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u0438\u043a', 'verbose_name_plural': '\u041f\u0440\u0435\u0434\u0448\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u0438\u043a\u0438'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '\u041f\u0440\u043e\u0435\u043a\u0442', 'verbose_name_plural': '\u041f\u0440\u043e\u0435\u043a\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='projectmember',
            options={'verbose_name': '\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a \u043f\u0440\u043e\u0435\u043a\u0442\u0430', 'verbose_name_plural': '\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0438 \u043f\u0440\u043e\u0435\u043a\u0442\u043e\u0432'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '\u0417\u0430\u0434\u0430\u0447\u0430', 'verbose_name_plural': '\u0417\u0430\u0434\u0430\u0447\u0438'},
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='\u0434\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430'),
        ),
    ]
