# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-24 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_auto_20170528_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='limit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u043a\u0440\u0430\u0439\u043d\u0438\u0439 \u0441\u0440\u043e\u043a'),
        ),
    ]
