# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-05 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_task_limit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='limit_date',
            new_name='soft_deadline',
        ),
    ]
