# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-05 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_auto_20171105_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hard_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u043a\u0440\u0430\u0439\u043d\u0438\u0439 \u0441\u0440\u043e\u043a (\u0436\u0435\u0441\u0442\u043a\u0438\u0439)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='soft_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u043a\u0440\u0430\u0439\u043d\u0438\u0439 \u0441\u0440\u043e\u043a (\u043c\u044f\u0433\u043a\u0438\u0439)'),
        ),
    ]
