# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-30 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_auto_20180425_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[(1, 'Tester'), (2, 'Developer'), (3, 'Designer'), (4, 'Manager')], default=2, max_length=128, verbose_name='\u0440\u043e\u043b\u044c'),
        ),
    ]
