# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-01 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_remove_projectmember_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.IntegerField(choices=[(1, 'Tester'), (2, 'Developer'), (3, 'Designer'), (4, 'Manager')], default=2, verbose_name='\u0440\u043e\u043b\u044c'),
        ),
    ]
